version: '3.5'

services:
  proxy:
    image: nginx:1.13.9-alpine
    ports:
      - "80:80"
    volumes:
      - ./resources/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "insight"
      
  insight:
    image: ifishgroup/insight:${TAG}
    depends_on:
      - "api"
    command: [ "${BASE_URL}" ]

  api:
    image: ifishgroup/insight-api:${TAG}
    depends_on:
      - "mongodb"
      - "userimport"
      - "settingsimport"
      - "articlesimport"
  
  mongodb:
    image: mongo:3.6.3
    ports:
      - "27017:27017"

  userimport:
    image: ifishgroup/insight-import:${TAG}
    depends_on:
      - mongodb
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "mongoimport", "--host", "mongodb", "--db", "Insight", "--collection", "users", "--type", "json", "--file", "insertUsers.json", "--drop", "--upsert", "--jsonArray"]

  settingsimport:
    image: ifishgroup/insight-import:${TAG}
    depends_on:
      - mongodb
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "mongoimport", "--host", "mongodb", "--db", "Insight", "--collection", "settings", "--type", "json", "--file", "insertSettings.json", "--drop", "--upsert", "--jsonArray"]

  articlesimport:
    image: ifishgroup/insight-import:${TAG}
    depends_on:
      - mongodb
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "mongoimport", "--host", "mongodb", "--db", "Insight", "--collection", "ka", "--type", "json", "--file", "insertArticles.json", "--drop", "--upsert", "--jsonArray"]