version: '3'

services:
  e2e:
    image: node:9.5.0
    user: 'node'
    working_dir: '/usr/src/'
    depends_on:
      - "pqvp-kmt"
      - "chrome"
      - "hub"
    volumes:
      - ./:/usr/src/
    command: ["./wait-for-it.sh", "hub:4444", "--", "bash", "-c", "yarn install && yarn e2e-docker"]

  pqvp-kmt:
    image: "ifishgroup/pqvp-kmt:${TAG}"

  chrome:
    image: selenium/node-chrome:3.9.1-actinium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.9.1-actinium
