version: '3'

volumes:
  db: {}

services:
  insight:
    image: ifishgroup/insight:${TAG}
    ports:
      - "80:80"
    depends_on:
      - "api"
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  api:
    image: ifishgroup/insight-api:${TAG}
    depends_on:
      - "mongodb"
    ports:
      - "3003:3003"
  
  mongodb:
    image: mongo:3.6.3
    working_dir: "/usr/src/"
    ports:
      - "27017:27017"
    volumes: 
      - db:/data/db