version: '3.5'

networks:
  web:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    attachable: true

volumes:
  db: {}

services:
  insight:
    image: ifishgroup/insight:${TAG}
    networks:
      - web
    ports:
      - "80:80"
    depends_on:
      - "api"
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  api:
    image: ifishgroup/insight-api:${TAG}
    networks:
      - web
      - backend
    ports:
      - "3003:3003"
    depends_on:
      - "mongodb"
  
  mongodb:
    image: mongo:3.6.3
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes: 
      - db:/data/db