version: '3.5'

networks:
  web:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    attachable: true

volumes:
  db: {}

services:
  insight:
    image: ifishgroup/insight:dev
    networks:
      - web
    ports:
      - "80:5000"
    depends_on:
      - "api"
    command: [ "${BASE_URL}" ]
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  api:
    image: ifishgroup/insight-api:dev
    networks:
      - web
      - backend
    ports:
      - "3003:3003"
    depends_on:
      - "mongodb"
      - "userimport"
      - "settingsimport"
      - "articlesimport"
  
  mongodb:
    image: mongo:3.6.3
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes: 
      - db:/data/db

  userimport:
    image: ifishgroup/insight-import:dev
    networks:
      - backend
    depends_on:
      - mongodb
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "mongoimport", "--host", "mongodb", "--db", "Insight", "--collection", "users", "--type", "json", "--file", "insertUsers.json", "--drop", "--upsert", "--jsonArray"]

  settingsimport:
    image: ifishgroup/insight-import:dev
    networks:
      - backend
    depends_on:
      - mongodb
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "mongoimport", "--host", "mongodb", "--db", "Insight", "--collection", "settings", "--type", "json", "--file", "insertSettings.json", "--drop", "--upsert", "--jsonArray"]

  articlesimport:
    image: ifishgroup/insight-import:dev
    networks:
      - backend
    depends_on:
      - mongodb
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "mongoimport", "--host", "mongodb", "--db", "Insight", "--collection", "ka", "--type", "json", "--file", "insertArticles.json", "--drop", "--upsert", "--jsonArray"]