module.exports = {
  'CM Can Publish KA 1': function (browser) {
    const devServer = browser.globals.devServerURL;
    console.log(devServer);
    browser
      .url(devServer)
      .maximizeWindow()
      .waitForElementPresent('i[class=ti-lock]', 5000)
      .assert.elementPresent('i[class=ti-lock]')
      .click('i[class=ti-lock]')
      .assert.elementPresent('input[id=email]')
      .setValue('input[id=email]', 'csmith@insight-kmt.com')
      .assert.elementPresent('input[id=password]')
      .setValue('input[id=password]', 'abcd1234!')
      .click('button[type=submit]')
      .waitForElementPresent('i[class=ti-unlock]', 5000)
      .assert.elementPresent('i[class=ti-unlock]')
      .click('i[class=ti-layers')
      .useXpath()
      .click('//a[text()="Edit"]')
      .waitForElementPresent('//table/tbody/tr[9]/th[2]/a[1]/i', 5000)
      .click('//table/tbody/tr[9]/th[2]/a[1]/i')
      .waitForElementPresent('//button[text()="Update"]', 5000)
      .assert.elementPresent('//button[text()="Update"]')
      .useCss()
      .waitForElementPresent('input[name=title]', 5000)
      .useXpath()
      .assert.elementPresent('//*[@id="app"]/div/div/div/section/div/div/div/div/div[2]/div/form/div[1]/div/div/button[1]')
      .click('//*[@id="app"]/div/div/div/section/div/div/div/div/div[2]/div/form/div[1]/div/div/button[1]')
      .pause(1000)
      .acceptAlert()
      .refresh()
      .useCss()
      .waitForElementPresent('button[type=submit]', 5000)
      .assert.elementPresent('button[type=submit]')
      .click('button[type=submit]')
      .waitForElementPresent('div[class="toast-container toast-top-full-width"]', 5000)
      .assert.elementPresent('div[class="toast-container toast-top-full-width"]')
      .refresh();
  },
  'CM can Improve KA 1': function (browser) {
    browser
      .waitForElementPresent('i[class=ti-layers]', 5000)
      .click('i[class=ti-layers')
      .useXpath()
      .click('//a[text()="Edit"]')
      .waitForElementPresent('//table/tbody/tr[9]/th[2]/a[1]/i', 5000)
      .click('//table/tbody/tr/th[2]/a[1]/i')
      .waitForElementPresent('//button[text()="Update"]', 5000)
      .assert.elementPresent('//button[text()="Update"]')
      .useCss()
      .waitForElementPresent('input[name=title]', 5000)
      .clearValue('input[name=title]')
      .setValue('input[name=title]', 'CM Improved - KA 1')
      .useXpath()
      .assert.elementPresent('//*[@id="app"]/div/div/div/section/div/div/div/div/div[2]/div/form/div[1]/div/div/button[1]')
      .click('//*[@id="app"]/div/div/div/section/div/div/div/div/div[2]/div/form/div[1]/div/div/button[1]')
      .pause(1000)
      .acceptAlert()
      .refresh()
      .useCss()
      .waitForElementPresent('button[type=submit]', 5000)
      .assert.elementPresent('button[type=submit]')
      .click('button[type=submit]')
      .waitForElementPresent('div[class="toast-container toast-top-full-width"]', 5000)
      .assert.elementPresent('div[class="toast-container toast-top-full-width"]')
      .refresh()
      .waitForElementPresent('i[class=ti-unlock]', 5000)
      .click('i[class=ti-unlock')
      .waitForElementPresent('i[class=ti-lock', 5000)
      .end();
  },
};
